services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - localcraft_mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  localcraft_mongo:
