{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "web-service.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}

  target:
    name: {{ include "web-service.fullname" . }}-secret
    creationPolicy: Owner
    deletionPolicy: Retain

  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.awsSecretName }}
{{- end }}